"""Supply-chain tooling - lockfile, SBOM and vulnerability scan.

Contributes to AUD-M-006: "No hash-locked lockfile, no SBOM, and the
vulnerability scan remains NOT VERIFIED."

Three subcommands:

    python tools/supply_chain.py lock    # hash-pinned requirements.lock from PyPI
    python tools/supply_chain.py sbom    # CycloneDX 1.5 JSON
    python tools/supply_chain.py audit   # OSV.dev vulnerability scan

Design note - why this is not just `pip-audit` and `pip-compile`
---------------------------------------------------------------
Those tools are the right answer in a normal environment and CI should prefer
them. This module exists so the work is reproducible where they are absent, and
because it makes the *inputs* explicit: the scan is over the project's declared
dependency set, not over whatever happens to be installed in the ambient
interpreter. An SBOM built from `importlib.metadata` in a shared virtualenv
describes that virtualenv, not this project, and would be actively misleading.

`lock` and `sbom` require the resolved transitive set. Resolution is pip's job:
run `pip install -r requirements-dev.txt` in a clean venv, then
`pip freeze > tools/resolved.txt`, and pass `--resolved tools/resolved.txt`.
Without it, only the declared direct dependencies are processed and the output
says so rather than pretending to completeness.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PYPI = "https://pypi.org/pypi/{name}/{version}/json"
OSV_BATCH = "https://api.osv.dev/v1/querybatch"

DIRECT_DEPENDENCIES = {
    "runtime": ["fastapi", "uvicorn", "pydantic"],
    "development": ["pytest", "httpx"],
}


def _get_json(url: str, timeout: int = 20) -> dict | None:
    try:
        with urllib.request.urlopen(url, timeout=timeout) as r:
            return json.loads(r.read())
    except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError):
        return None


def installed_version(name: str) -> str | None:
    from importlib.metadata import PackageNotFoundError, version

    try:
        return version(name)
    except PackageNotFoundError:
        return None


def read_resolved(path: Path | None) -> list[tuple[str, str]]:
    """Parse a `pip freeze` file into (name, version) pairs."""
    if path is None or not path.exists():
        return []
    out = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("-"):
            continue
        m = re.match(r"^([A-Za-z0-9._-]+)==([^\s;]+)", line)
        if m:
            out.append((m.group(1), m.group(2)))
    return out


def target_packages(resolved: Path | None) -> tuple[list[tuple[str, str]], bool]:
    """Return (packages, is_complete_transitive_set)."""
    pairs = read_resolved(resolved)
    if pairs:
        return pairs, True
    direct = []
    for names in DIRECT_DEPENDENCIES.values():
        for n in names:
            v = installed_version(n)
            if v:
                direct.append((n, v))
    return sorted(set(direct)), False


# ---------------------------------------------------------------- lock
def cmd_lock(args) -> int:
    packages, complete = target_packages(args.resolved)
    if not packages:
        print("No packages resolved. Install the project dependencies first.")
        return 1

    lines = [
        "# requirements.lock - hash-pinned dependency lock",
        "# Generated by tools/supply_chain.py lock. Do not edit by hand.",
        "#",
        "# Install with:   pip install --require-hashes -r requirements.lock",
        "#",
        f"# Transitive closure complete: {complete}",
    ]
    if not complete:
        lines += [
            "# WARNING - this lock covers DECLARED DIRECT dependencies only.",
            "#           Regenerate with --resolved <pip-freeze-output> from a clean",
            "#           virtualenv to obtain the full transitive set.",
        ]
    lines.append("")

    missing = []
    for name, version in packages:
        meta = _get_json(PYPI.format(name=name, version=version))
        if not meta:
            missing.append(f"{name}=={version}")
            continue
        digests = [
            f["digests"]["sha256"]
            for f in meta.get("urls", [])
            if f.get("digests", {}).get("sha256")
        ]
        if not digests:
            missing.append(f"{name}=={version}")
            continue
        entry = f"{name}=={version}"
        for i, d in enumerate(sorted(set(digests))):
            entry += f" \\\n    --hash=sha256:{d}"
        lines.append(entry)

    out = ROOT / "requirements.lock"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out.relative_to(ROOT)} - {len(packages) - len(missing)} pinned.")
    if missing:
        print(f"Could not retrieve hashes for: {', '.join(missing)}")
    return 0


# ---------------------------------------------------------------- sbom
def cmd_sbom(args) -> int:
    packages, complete = target_packages(args.resolved)
    components = []
    for name, version in packages:
        meta = _get_json(PYPI.format(name=name, version=version)) or {}
        info = meta.get("info", {})
        components.append({
            "type": "library",
            "name": name,
            "version": version,
            "purl": f"pkg:pypi/{name.lower()}@{version}",
            "licenses": (
                [{"license": {"name": info["license"]}}]
                if info.get("license") else []
            ),
            "description": (info.get("summary") or "")[:200],
        })

    sbom = {
        "bomFormat": "CycloneDX",
        "specVersion": "1.5",
        "version": 1,
        "metadata": {
            "component": {
                "type": "application",
                "name": "capex-wbs-control-hub",
                "description": "CAPEX & WBS Control Hub",
            },
            "properties": [
                {"name": "transitive_closure_complete", "value": str(complete).lower()},
                {
                    "name": "generation_note",
                    "value": (
                        "Direct declared dependencies only. Regenerate with "
                        "--resolved from a clean virtualenv for the full set."
                    ) if not complete else "Full resolved dependency set.",
                },
            ],
        },
        "components": components,
    }
    out = ROOT / "sbom.cyclonedx.json"
    out.write_text(json.dumps(sbom, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {out.relative_to(ROOT)} - {len(components)} components, "
          f"complete={complete}")
    return 0


# ---------------------------------------------------------------- audit
def cmd_audit(args) -> int:
    """Query OSV.dev - the same vulnerability database pip-audit uses."""
    packages, complete = target_packages(args.resolved)
    if not packages:
        print("No packages resolved.")
        return 1

    queries = [
        {"package": {"name": n, "ecosystem": "PyPI"}, "version": v}
        for n, v in packages
    ]
    body = json.dumps({"queries": queries}).encode()
    req = urllib.request.Request(
        OSV_BATCH, data=body, headers={"Content-Type": "application/json"}
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            results = json.loads(r.read()).get("results", [])
    except Exception as exc:  # noqa: BLE001 - report, do not mask
        print(f"OSV query failed: {type(exc).__name__}: {exc}")
        return 1

    findings = []
    for (name, version), result in zip(packages, results):
        for vuln in result.get("vulns", []) or []:
            findings.append({"package": name, "version": version, "id": vuln.get("id")})

    report = {
        "scanned_at_note": "Run date is recorded by CI, not embedded here.",
        "database": "OSV.dev",
        "transitive_closure_complete": complete,
        "packages_scanned": len(packages),
        "findings": findings,
    }
    out = ROOT / "vulnerability-report.json"
    out.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    print(f"Scanned {len(packages)} package(s) against OSV.dev "
          f"(transitive closure complete: {complete})")
    for name, version in packages:
        print(f"  {name}=={version}")
    if findings:
        print(f"\n{len(findings)} vulnerability finding(s):")
        for f in findings:
            print(f"  {f['package']}=={f['version']}  {f['id']}")
        return 1
    print("\nNo known vulnerabilities in the scanned set.")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    sub = p.add_subparsers(dest="command", required=True)
    for name, fn in (("lock", cmd_lock), ("sbom", cmd_sbom), ("audit", cmd_audit)):
        s = sub.add_parser(name)
        s.add_argument(
            "--resolved", type=Path, default=None,
            help="pip freeze output giving the full transitive set",
        )
        s.set_defaults(func=fn)
    args = p.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
